name: overshare2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/logo.png"
    - "assets/signupsuccess.png"
    - "assets/minilogo.png"
    - "assets/landing/landingbg.png"
    - "assets/landing/asset1.png"
    - "assets/login/asset1.png"
    - "assets/homepage/asset1.png"
    - "assets/homepage/asset2.png"
    - "assets/aboutus/Star.png"
    - "assets/aboutus/asset1.png"
    - "assets/aboutus/dejan.jpeg"
    - "assets/aboutus/luthfi.jpg"
    - "assets/props/star.png"
    - "assets/props/success_snapbar.png"
    - "assets/props/error_snapbar.png"
    - "assets/props/error.png"
    - "assets/"
