// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeiiIH3Ui9V3L0hPcxgsIO3ZOWaw1d3sU',
    appId: '1:1034050188047:android:4bebbad3dcd82d2714047a',
    messagingSenderId: '1034050188047',
    projectId: 'overshare2-3266e',
    storageBucket: 'overshare2-3266e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4XPDa_hvdd2vQsQQV6Jc3N2cBsiWcv4',
    appId: '1:1034050188047:ios:288c96d9f5da450c14047a',
    messagingSenderId: '1034050188047',
    projectId: 'overshare2-3266e',
    storageBucket: 'overshare2-3266e.appspot.com',
    iosBundleId: 'com.example.overshare2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH4XPDa_hvdd2vQsQQV6Jc3N2cBsiWcv4',
    appId: '1:1034050188047:ios:288c96d9f5da450c14047a',
    messagingSenderId: '1034050188047',
    projectId: 'overshare2-3266e',
    storageBucket: 'overshare2-3266e.appspot.com',
    iosBundleId: 'com.example.overshare2',
  );
}
